# Generated by Django 5.2.14 on 2026-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("ingredientes", models.CharField(max_length=150)),
                ("pasos_elaboracion", models.CharField(max_length=250)),
            ],
        ),
    ]
