# Generated by Django 5.2.14 on 2026-05-27 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receta",
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.AddField(
            model_name="receta",
            name="autor",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recetas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receta",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="receta",
            name="tiempo_preparacion",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receta",
            name="ingredientes",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="receta",
            name="pasos_elaboracion",
            field=models.TextField(max_length=550),
        ),
    ]
