# Generated by Django 5.2.10 on 2026-06-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0004_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recetas.categoria",
            ),
        ),
    ]
